export const MAGE_LIFE_DEFAULT = 12;
export const MAGE_SKILL_DEFAULT = 6;
export const MAGE_STRENGTH_DEFAULT = 5;
export const MAGE_INTELLIGENCE_DEFAULT = 10;

export const MAGE_ATTACK_SKILL_PERCENTAGE = 0.5;
export const MAGE_ATTACK_STRENGTH_PERCENTAGE = 0.2;
export const MAGE_ATTACK_INTELLIGENCE_PERCENTAGE = 1.5;

export const MAGE_SPEED_SKILL_PERCENTAGE = 0.5;
export const MAGE_SPEED_STRENGTH_PERCENTAGE = 0.2;

export const THIEF_LIFE_DEFAULT = 15;
export const THIEF_SKILL_DEFAULT = 10;
export const THIEF_STRENGTH_DEFAULT = 4;
export const THIEF_INTELLIGENCE_DEFAULT = 4;

export const THIEF_ATTACK_SKILL_PERCENTAGE = 1;
export const THIEF_ATTACK_STRENGTH_PERCENTAGE = 0.25;
export const THIEF_ATTACK_INTELLIGENCE_PERCENTAGE = 0.25;

export const THIEF_SPEED_SKILL_PERCENTAGE = 0.8;

export const WARRIOR_LIFE_DEFAULT = 20;
export const WARRIOR_SKILL_DEFAULT = 5;
export const WARRIOR_STRENGTH_DEFAULT = 10;
export const WARRIOR_INTELLIGENCE_DEFAULT = 5;

export const WARRIOR_ATTACK_SKILL_PERCENTAGE = 0.2;
export const WARRIOR_ATTACK_STRENGTH_PERCENTAGE = 0.8;

export const WARRIOR_SPEED_SKILL_PERCENTAGE = 0.6;
export const WARRIOR_SPEED_INTELLIGENCE_PERCENTAGE = 0.2;
